tasks:
  - init: curl -O https://hyperland.s3.amazonaws.com/hyper
    command: |
      chmod +x ./hyper
      ./hyper
  - init: yarn
    command: |
      export HMR_HOST=`gp url 24678`
      yarn setup
      yarn dev

ports:
  - port: 24678
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
  - port: 6363
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
